import type { Metadata } from "next";
import SubpageHeader from "@/components/layout/SubpageHeader";

export const metadata: Metadata = {
  title: "Legal — PetrolSaver",
  description: "Terms of use and privacy policy for PetrolSaver, a fuel price comparison tool for Victoria and New South Wales, Australia.",
  alternates: { canonical: "/legal" },
};

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-[var(--background)]">
      <SubpageHeader />
      <div className="max-w-3xl mx-auto px-4 py-10">
        <h1 className="text-2xl font-bold text-[var(--foreground)] mb-2">Legal</h1>
        <p className="text-xs text-[var(--muted)] mb-6">Last updated: 20 March 2026</p>

        {/* Jump links */}
        <div className="flex gap-3 mb-8 text-xs">
          <a href="#terms" className="text-[var(--accent-text)] hover:text-[var(--foreground)] transition-colors">Terms of Use</a>
          <span className="text-[var(--muted)]">&middot;</span>
          <a href="#privacy" className="text-[var(--accent-text)] hover:text-[var(--foreground)] transition-colors">Privacy Policy</a>
        </div>

        {/* ─── Terms ─── */}
        <div id="terms" className="scroll-mt-20">
          <h2 className="text-xl font-bold text-[var(--foreground)] mb-4 pb-2 border-b border-[var(--subtle-border)]">Terms of Use</h2>
          <div className="space-y-5 text-sm text-[var(--muted)] leading-relaxed mb-12">
            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">1. About PetrolSaver</h3>
              <p>
                PetrolSaver (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is a free fuel price comparison
                tool for Victoria and New South Wales, Australia. We display fuel price data sourced from the Victorian
                Government&apos;s Fair Fuel Open Data API (Service Victoria) and the NSW FuelCheck API (Transport for NSW).
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">2. Data Accuracy</h3>
              <p>
                Fuel prices are sourced from the Victorian and NSW governments.
                Victorian prices are delayed ~24 hours; NSW prices are real-time.
                We do not modify price data. While we strive for accuracy, we cannot guarantee all prices are
                current or correct. Confirm prices directly with the station before purchasing.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">3. Recommendations</h3>
              <p>
                Recommendations are generated by an algorithm that considers price, distance, your vehicle&apos;s
                consumption, fill amount, and detour costs. These are estimates only.
                Your actual savings may vary based on your vehicle, driving conditions, and route.
                PetrolSaver is not a navigation service.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">4. No Warranty</h3>
              <p>
                PetrolSaver is provided &ldquo;as is&rdquo; without warranty of any kind.
                We do not warrant the service will be uninterrupted or error-free. Use is at your own risk.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">5. Limitation of Liability</h3>
              <p>
                To the maximum extent permitted by law, PetrolSaver shall not be liable for any damages arising from
                your use of the service, including financial losses from fuel purchasing decisions based on our recommendations.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">6. Independence</h3>
              <p>
                PetrolSaver is not affiliated with any fuel retailer or government. Recommendations are
                generated algorithmically without commercial influence.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">7. Advertising</h3>
              <p>
                We display ads via Google AdSense to support free operation.
                Advertisements are not endorsements.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">8. Changes</h3>
              <p>
                We may update these terms at any time. Continued use constitutes acceptance.
              </p>
            </section>
          </div>
        </div>

        {/* ─── Privacy ─── */}
        <div id="privacy" className="scroll-mt-20">
          <h2 className="text-xl font-bold text-[var(--foreground)] mb-4 pb-2 border-b border-[var(--subtle-border)]">Privacy Policy</h2>
          <div className="space-y-5 text-sm text-[var(--muted)] leading-relaxed mb-8">
            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">Summary</h3>
              <p>
                PetrolSaver is designed with privacy in mind. We don&apos;t store your location,
                don&apos;t track your movements, and don&apos;t sell your data.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">Location Data</h3>
              <p>
                Your location is used only in your browser to calculate distances.
                It is <strong className="text-[var(--foreground)]">never sent to our servers</strong>, stored, or shared.
                Discarded when you close the page. If denied, defaults to Melbourne CBD.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">Local Storage</h3>
              <p>We use browser localStorage to remember your preferences (vehicle, fuel type, location, flagged stations). This data stays on your device.</p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">Feedback &amp; Flags</h3>
              <p>
                Feedback and station flags are sent to our team via email. No personal information is attached.
                If you sign up for price alerts, your email is stored with Resend (our email provider) and used solely for notifications.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">Analytics &amp; Advertising</h3>
              <p>
                We use Vercel Analytics (privacy-focused, no cookies). Google AdSense may use cookies for ad targeting — manage preferences at{" "}
                <a href="https://adssettings.google.com" target="_blank" rel="noopener noreferrer" className="text-[var(--accent-text)] hover:text-[var(--foreground)]">
                  Google Ad Settings
                </a>.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">Third-Party Services</h3>
              <p>Service Victoria, Transport for NSW, OpenStreetMap/CartoDB, Nominatim, OpenRouteService, Vercel, Google AdSense, Resend, Supabase.</p>
            </section>

            <section>
              <h3 className="text-sm font-bold text-[var(--foreground)] mb-1.5">Contact</h3>
              <p>
                Questions? Email{" "}
                <a href="mailto:petrolsaver.live@gmail.com" className="text-[var(--accent-text)] hover:text-[var(--foreground)]">
                  petrolsaver.live@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>

        <div className="pt-6 border-t border-[var(--subtle-border)] text-center text-[10px] text-[var(--muted)]">
          <a href="/how-it-works" className="text-[var(--accent-text)] hover:text-[var(--foreground)]">How It Works</a>
        </div>
      </div>
    </div>
  );
}
