import type { Metadata } from "next";
import SubpageHeader from "@/components/layout/SubpageHeader";

export const metadata: Metadata = {
  title: "Terms of Use — PetrolSaver",
  description: "Terms and conditions for using PetrolSaver, a fuel price comparison tool for Victoria, Australia.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#1a1a1a]">
      <SubpageHeader />
      <div className="max-w-3xl mx-auto px-4 py-10">
        <h1 className="text-2xl font-bold text-white mb-6">Terms of Use</h1>
        <p className="text-xs text-[#5f6368] mb-8">Last updated: 16 March 2026</p>

        <div className="space-y-6 text-sm text-[#9aa0a6] leading-relaxed">
          <section>
            <h2 className="text-base font-bold text-white mb-2">1. About PetrolSaver</h2>
            <p>
              PetrolSaver (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is a free fuel price comparison
              tool for Victoria, Australia. We display fuel price data sourced from the Victorian
              Government&apos;s Fair Fuel Open Data API, operated by Service Victoria.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">2. Data Accuracy</h2>
            <p>
              Fuel prices displayed on PetrolSaver are sourced from the Victorian Government and are
              subject to a delay of approximately 24 hours. We do not modify the price data in any way.
              While we strive to provide accurate information, we cannot guarantee that all prices are
              current or correct at the time you view them.
            </p>
            <p className="mt-2">
              Prices, availability, and station information may change without notice. We recommend
              confirming prices directly with the fuel station before making purchasing decisions based
              solely on the information provided by PetrolSaver.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">3. Recommendations</h2>
            <p>
              Our station recommendations are generated by an algorithm that considers price, distance,
              estimated fuel consumption, and detour costs. These recommendations are estimates only and
              are based on average assumptions (8.5L/100km consumption, 55L tank, 1.35x road distance factor).
              Your actual savings may vary based on your vehicle, driving conditions, and route taken.
            </p>
            <p className="mt-2">
              PetrolSaver is not a navigation service. &ldquo;Get Directions&rdquo; links open Google Maps
              in a new window. We are not responsible for routing, traffic conditions, or navigation accuracy.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">4. No Warranty</h2>
            <p>
              PetrolSaver is provided &ldquo;as is&rdquo; without warranty of any kind, express or implied.
              We do not warrant that the service will be uninterrupted, error-free, or free of harmful components.
              Use of PetrolSaver is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">5. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, PetrolSaver and its operators shall not be liable
              for any direct, indirect, incidental, consequential, or special damages arising from
              your use of the service, including but not limited to financial losses from fuel purchasing
              decisions made based on our recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">6. Third-Party Services</h2>
            <p>
              PetrolSaver uses third-party services including Google Maps (for directions), Google AdSense
              (for advertising), OpenStreetMap (for map tiles), Nominatim (for geocoding), and Resend
              (for email notifications). Your use of these services is subject to their respective terms
              and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">7. Independence</h2>
            <p>
              PetrolSaver is not affiliated with, endorsed by, or sponsored by any fuel retailer, fuel brand,
              or the Victorian Government. Our recommendations are generated algorithmically without any
              commercial influence from fuel companies.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">8. Advertising</h2>
            <p>
              PetrolSaver displays advertisements via Google AdSense to support the free operation of the
              service. These advertisements are served by Google and are not controlled by PetrolSaver.
              The appearance of an advertisement does not constitute an endorsement.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">9. Changes to Terms</h2>
            <p>
              We reserve the right to update these terms at any time. Continued use of PetrolSaver after
              changes are posted constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white mb-2">10. Contact</h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a href="mailto:petrolsaver.live@gmail.com" className="text-[#8ab4f8] hover:text-[#aecbfa]">
                petrolsaver.live@gmail.com
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-white/5 text-center text-[10px] text-[#5f6368]">
          <a href="/privacy" className="text-[#8ab4f8] hover:text-[#aecbfa]">Privacy Policy</a>
          {" "}&middot;{" "}
          <a href="/how-it-works" className="text-[#8ab4f8] hover:text-[#aecbfa]">How It Works</a>
        </div>
      </div>
    </div>
  );
}
